CREATE DATABASE FIDO2;
USE FIDO2;
SHOW DATABASES; 

-- TẠO BẢNG USER
CREATE TABLE USERS (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_HANDLE VARBINARY(64) NOT NULL UNIQUE,
    USERNAME VARCHAR(100) NOT NULL UNIQUE,
    DISPLAY_NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE
);

-- TẠO BẢNG CREDENTIALS
CREATE TABLE CREDENTIALS (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    CREDENTIAL_ID VARBINARY(255) NOT NULL UNIQUE,
    PUBLIC_KEY BLOB NOT NULL, -- DÙNG BLOB HOẶC TĂNG VARBINARY LÊN 1024
    SIGN_COUNT INT NOT NULL DEFAULT 0,
    USER_ID INT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);
       
SELECT * FROM USERS;
SELECT * FROM CREDENTIALS;

DROP TABLE USERS;
DROP TABLE CREDENTIALS;

DELETE FROM USERS WHERE USERNAME = 'thu';